version: '3.8'

services:
  backend:
    build: ./quiz_maker
    ports:
      - "5000:5000"
    volumes:
      - ./quiz_maker:/app
    networks:
      - my-network

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
